# Netlify Configuration
# This file should be in the root of your repository

[build]
  # Build command (if any)
  command = ""
  
  # Directory to deploy (relative to root)
  publish = "protfile"
  
  # Base directory for build
  base = ""

# Redirect rules
[[redirects]]
  from = "/cv"
  to = "/assets/Methush_Anjula_CV.pdf"
  status = 200

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers for images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"